---
- name: configure npm install for windows
  shell: "cd /vagrant/server ; npm install --no-bin-links"
- name: start server
  shell: "docker rm -f server ; docker run -d --name server -v /vagrant/server:/usr/src/app -w /usr/src/app -p 3000:3000 node:6-onbuild "