---
- name: vagrant
  hosts: all
  roles: 
    - { role : nodejs, tags : 'infrequent' }
    - mongo
    - server
#  pre_tasks:
#    - name: test
#      shell: "curl -sL https://deb.nodesource.com/setup_6.x | sudo -E bash -"
#    - shell: "sudo apt-get install -y nodejs"